name: dart_lol
description: A Flutter package for League of Legends made in Germany with happiness!
version: 0.3.0
homepage: https://github.com/EmiDevGerman/dart_lol
#flutter pub publish

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  http: ^0.13.4
  isar: ^2.1.4
  isar_flutter_libs: ^2.1.4
  localstorage: ^4.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^2.1.4
  build_runner: ^2.1.7
  # linting in flutter
  flutter_lints: ^1.0.4