name: dart_lol
description: A Flutter package for League of Legends made in Germany with happiness!
version: 0.2.0
homepage: https://github.com/EmiDevGerman/dart_lol
#flutter pub publish

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  isar: 0.4.0
  isar_flutter_libs: 0.4.0 # contains the binaries
  localstorage: ^4.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.0.0
  isar_generator: 0.4.0
  build_runner: any

flutter: