name: dart_lol
description: A Flutter package for League of Legends made in Germany with happiness!
version: 0.2.0
homepage: https://github.com/EmiDevGerman/dart_lol
#flutter pub publish

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.0.0

flutter:
